services:
  db:
    image: pgvector/pgvector:pg16
    container_name: dynarag_db
    restart: always
    ports:
      - "5053:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
volumes:
  local_pgdata:
